# Generated by Django 2.0 on 2020-03-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_address', models.TextField(blank=True)),
                ('ship_address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(blank=True, default=False, null=True)),
                ('customer_number', models.IntegerField(blank=True, default=False, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cat', models.IntegerField(blank=True, default=False, null=True)),
                ('ship_days', models.IntegerField(blank=True, default=False, null=True)),
                ('travel_days', models.IntegerField(blank=True, default=False, null=True)),
                ('order_total', models.IntegerField(blank=True, default=False, null=True)),
                ('estimated_costs', models.IntegerField(blank=True, default=False, null=True)),
                ('line_number', models.IntegerField(default=False, null=True)),
                ('part_number', models.IntegerField(default=False, null=True)),
                ('description', models.TextField(blank=True)),
                ('whse', models.IntegerField(blank=True, null=True)),
                ('alloc', models.TextField(blank=True)),
                ('qty_order', models.IntegerField(default=False, null=True)),
                ('qty_avail', models.IntegerField(blank=True, default=False, null=True)),
                ('required_date', models.DateField()),
                ('promised_date', models.DateField(blank=True)),
                ('unit_price', models.FloatField(default=False, null=True)),
                ('ship_tolerance_min', models.IntegerField(blank=True, default=False, null=True)),
                ('ship_tolerance_max', models.IntegerField(blank=True, default=False, null=True)),
                ('uos', models.IntegerField(blank=True, default=False, null=True)),
                ('price_book', models.IntegerField(blank=True, default=False, null=True)),
                ('stat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order', models.IntegerField()),
                ('bill_address', models.TextField(blank=True)),
                ('ship_address', models.TextField(blank=True)),
                ('required_date', models.DateField()),
                ('freight', models.CharField(max_length=50)),
                ('quote', models.CharField(max_length=50)),
                ('contract', models.IntegerField()),
                ('order_status', models.CharField(max_length=50)),
                ('order_received', models.CharField(max_length=50)),
                ('price_method', models.CharField(max_length=50)),
                ('surcharge', models.CharField(max_length=50)),
                ('A_R_credit', models.CharField(max_length=50)),
                ('fax_ASN', models.CharField(max_length=50)),
                ('email_ASN', models.CharField(max_length=50)),
                ('order_type', models.CharField(max_length=50)),
                ('order_number', models.IntegerField(blank=True, default=1, null=True)),
                ('ordered_date', models.DateField(blank=True)),
                ('price_details', models.TextField(blank=True)),
                ('kit_details', models.TextField(blank=True)),
                ('ship_via', models.TextField(blank=True)),
                ('attention', models.TextField(blank=True)),
                ('ship_instructions', models.TextField(blank=True)),
                ('F_O_B', models.TextField(blank=True)),
                ('warehouse', models.IntegerField(blank=True, null=True)),
                ('sales_rep', models.CharField(blank=True, max_length=50)),
                ('product_line', models.TextField(blank=True)),
                ('COS_project', models.IntegerField(blank=True, null=True)),
                ('sales_account', models.IntegerField(blank=True, null=True)),
                ('order_value', models.IntegerField(blank=True, null=True)),
                ('staus_number', models.IntegerField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('ship_cond', models.IntegerField(blank=True, null=True)),
                ('credit_control', models.IntegerField(blank=True, null=True)),
                ('ASN_contact', models.TextField(blank=True)),
                ('ASN_title', models.TextField(blank=True)),
                ('ASN_fax_num', models.IntegerField(blank=True, null=True)),
                ('email_addr', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('die', models.FloatField(default=False, null=True)),
                ('billet_alloy', models.FloatField(default=False, null=True)),
                ('paint_lbs', models.FloatField(default=False, null=True)),
                ('paint_sqft', models.FloatField(default=False, null=True)),
                ('anodizing', models.FloatField(default=False, null=True)),
                ('thermal_break', models.FloatField(default=False, null=True)),
                ('exagrip', models.FloatField(default=False, null=True)),
                ('masking', models.FloatField(default=False, null=True)),
                ('packaging', models.FloatField(default=False, null=True)),
                ('price_time', models.IntegerField(default=False, null=True)),
                ('ingot_price', models.FloatField(default=False, null=True)),
                ('conversion_factor', models.FloatField(default=False, null=True)),
                ('total_price', models.FloatField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_address', models.TextField(blank=True)),
            ],
        ),
    ]
