# Generated by Django 2.0 on 2020-03-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='estimated_costs',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ship_days',
        ),
        migrations.RemoveField(
            model_name='order',
            name='travel_days',
        ),
        migrations.AddField(
            model_name='line',
            name='cat',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='customer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='customer_number',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='estimated_costs',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='order_number',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='order_total',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='ship_days',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='travel_days',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sales_rep',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='ship_address',
            field=models.TextField(blank=True),
        ),
    ]
